{
 "title": "Shelly",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Current Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"value\" AS \"H.Room\"\nFROM \"homeassistant\".\"autogen\".\"%\"\nWHERE \"entity_id\" = 'shelly_blu_h_t_7cc6b673811c_humidity'\nORDER BY time DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Humidity Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "SELECT mean(\"value\") AS \"H.Room\"\nFROM \"homeassistant\".\"autogen\".\"%\"\nWHERE $timeFilter\n  AND \"entity_id\" = 'shelly_blu_h_t_7cc6b673811c_humidity'\nGROUP BY time($__interval)\nFILL(null)"
    }
   ]
  },
  {
   "title": "EM1 Active Power (W)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"value\" AS \"W.EM1\"\nFROM \"homeassistant\".\"autogen\".\"W\"\nWHERE \"entity_id\" = 'shelly_pro_em_08f9e0e78964_em1_active_power'\nORDER BY time DESC\nLIMIT 1\n"
    }
   ]
  },
  {
   "title": "Current Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"value\" AS \"T.Room\"\nFROM \"homeassistant\".\"autogen\".\"°C\"\nWHERE \"entity_id\" = 'shelly_blu_h_t_7cc6b673811c_temperature'\nORDER BY time DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Room Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "SELECT \"value\" AS \"T.Room\"\nFROM \"homeassistant\".\"autogen\".\"°C\"\nWHERE $timeFilter\n  AND \"entity_id\" = 'shelly_blu_h_t_7cc6b673811c_temperature'"
    }
   ]
  },
  {
   "title": "Active Power Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "query": "SELECT \"value\" AS \"EM1\"\nFROM \"homeassistant\".\"autogen\".\"W\"\nWHERE $timeFilter\n  AND \"entity_id\" = 'shelly_pro_em_08f9e0e78964_em1_active_power'\n"
    }
   ]
  }
 ]
}